# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13eb76f6a088bba3e2b7edfa26fa0dd8221823582aa7cac7e10ac8935da724c3ee36412f1754a89330f3d32ed1120ee03c37c48de6533bc1aa452dc6af1cac1e

test:
  secret_key_base: f9aebed160814422f05d551f300a31b42805acad9683f7a541b1724a148b8f2bec7d9ba99601b8a47890ce2083d9f4960ab489ff26fb6657c1bd5a9fc6c97a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
